version: '3'
services:
  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - '8080:8080'
    environment:
      - MONGO_URL=mongodb://mongo:27017/auth
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
